language: node_js
node_js:
  - "node"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

install:
  - npm install

script:
  - ng build --prod

after_success:
  - npm run lh -- https://pirac.es

notifications:
  email:
    on_failure: change
    on_success: change
