language: node_js
node_js:
  - "node"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build

notifications:
  email:
    on_failure: change
    on_success: change
